### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by TomaszKot11** [mbartn/banksystem#1]

**Comment by mbartn** [comment]
Let's fix this together @TomaszKot11

**Comment by TomaszKot11** [comment]
Okay

**Comment by TomaszKot11** [comment]
Call me

**Comment by mbartn** [comment]
@TomaszKot11 https://open.spotify.com/track/4PuyjJwylMhU1ztL5CIPSi?si=L7X1FdhSQrmEHSAbNX_OQQ

**Comment by TomaszKot11** [comment]
It was on melanż it was on melanż, bo to dobrze przetłumaczone ?

**Comment by TomaszKot11** [comment]
@mbartn

**Comment by TomaszKot11** [comment]
Bo ty mieszkasz w Polsce?

**Comment by mbartn** [comment]
tak dobrze przetlumaczyles i zrozumiale

**Comment by mbartn** [comment]
nie ja mieszkam w domu arnolda

**Comment by mbartn** [comment]
DWIC

**Comment by mbartn** [comment]
@TomaszKot11 i would like to offer you a job. We are creating the first application in the world that use innovative DWIC approach. Are you interested?

**Comment by TomaszKot11** [comment]
do you use MVC design pattern?

**Comment by TomaszKot11** [comment]
@mbartn

**Comment by TomaszKot11** [comment]
BTW nice profile emoji, are you a monkey ?

**Comment by mbartn** [comment]
to culturally have...

**Comment by mbartn** [comment]
@TomaszKot11 no im not

**Comment by mbartn** [comment]
Sorry we only use the DWIC pattern
